//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public int package_id { get; set; }
        public double package_price { get; set; }
        public Nullable<int> subject1 { get; set; }
        public Nullable<int> subject2 { get; set; }
        public Nullable<int> subject3 { get; set; }
        public Nullable<int> subject4 { get; set; }
        public Nullable<int> subject5 { get; set; }
    }
}
