//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceTC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Student
    {
        [DisplayName("Identification Card No.")]
        public string student_ic { get; set; }

        [DisplayName("Student Name")]
        public string student_name { get; set; }

        [DisplayName("Student Name (Chinese)")]
        public string student_cname { get; set; }

        [DisplayName("Package")]
        public int student_package { get; set; }

        [DisplayName("Students Parent IC")]
        public string parent_ic { get; set; }
    }
}
